<!-- Main css style -->
<link rel="stylesheet" href="<?=App::config('url')?>assets/css/mainStyle.css">

<!-- Main script style -->
<script src="<?=App::config('url')?>assets/js/mainScripts.js"></script>

<!-- Bootstrap 5.2 -->
<link rel="stylesheet" href="<?=App::config('url')?>assets/Bootstrap/bootstrap.css">
<script src="<?=App::config('url')?>assets/Bootstrap/bootstrap.js"></script>

<!-- FontAwesome 5 -->
<link rel="stylesheet" href="https://matej.com.hr/FontAwesome/css/all.css">
<script src="https://matej.com.hr/FontAwesome/js/all.js"></script>