<!doctype html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Project name</title>

    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php require 'headCss.phtml'?>
</head>
<body>
<div class="container">
    <p>Bootstrap 5 test</p>
    <br>
    <p>FontAwesome test: <i class="fas fa-globe-asia fa-2x"></i></p>
    <br>
    <p>Custom style test: <span class="testStyle">test</span></p>
</div>

<?php require 'footer.phtml'?>
</body>
</html>