name: Production deploy

on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name:  Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: #set your server url here
          username: #set your server username here
          server-dir: #set your server path here
          password: #set your server password here
          exclude: |
            **/.gitignore