<!doctype html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Project name</title>

    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php require 'headCss.phtml' ?>

    <script src="https://cdn.tiny.cloud/1/1v05vfl8eqtjxz89tzwpzvx1cw0enxxk9hjoqz6e9yuzp54c/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body>
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'anchor autolink charmap codesample emoticons link lists searchreplace table visualblocks wordcount',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
    });
</script>


<div class="container">
    <p>Bootstrap 5 test</p>
    <br>
    <p>FontAwesome test: <i class="fas fa-globe-asia fa-2x"></i></p>
    <br>
    <p>Custom style test: <span class="testStyle">test</span></p>

    <form action="<?=App::config('url')?>Login/login" method="post">
        <input type="email" name="email" required>
        <input type="password" name="password" required>
        <input type="submit" placeholder="submit" value="submit">
    </form>
    <?= isset($_GET['m']) && $_GET['m'] === '1' ? 'Pogrešna email adresa ili lozinka' : ''?>

    <?php
    if (Session::getInstance()->isLoggedIn()):
        var_dump(Session::getInstance()->getName());
    ?>
        <br>
        <a href="<?=App::config('url')?>Login/logout">logout</a>
    <?php endif;?>
</div>

<textarea>
  Welcome to TinyMCE!
</textarea>

<?php require 'footer.phtml' ?>
</body>
</html>