<!doctype html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Project name</title>

    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php require 'headCss.phtml' ?>
</head>

<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">


    <?php require "navbar.phtml"?>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <?php require "side_navbar.phtml"?>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Kontrolna ploča</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <a href="" class="nav-link"></a>

                            <li class="breadcrumb-item"><a href="<?=App::config('url')?>">Trgovina</a></li>
                            <li class="breadcrumb-item active">Nadzorna ploča</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Info boxes -->
                <?php require 'header.phtml'?>
                <!-- /.row -->


                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Kategorija - uređivanje slike</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <div class="row">
                                        <div class="col-6 text-center" style="padding: 5%"><img src="<?= App::config("url") ?>assets/images/productImages/<?=$category['image']?>" alt="" style="width: 100%"></div>
                                        <div class="col-5 text-left" style="width: 80%; margin-top: 10%">
                                            <label class="custom-file-label" for="exampleInputFile">Odabir slike</label>
                                            <input type="file" name="myfile" class="custom-file-input" id="exampleInputFile" form="update" >
                                        </div>
                                    </div>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->

                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->
                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Kategorija - brisanje</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <section>
                                        <div class="mt-5 text-center" style="padding-left: 10%; padding-right: 10%">
                                            <div class="form-group">
                                                <a href="<?=App::config('url')?>Category/deleteCategory/<?=$id?>" class="btn btn-danger">Obriši kategoriju</a>
                                            </div>
                                        </div>
                                    </section>

                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->

                            <!-- /.card-footer -->
                        </div>

                    </div>
                    <!-- /.col -->

                    <div class="col-md-4">

                        <!-- PRODUCT LIST -->
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Uređivanje kategorije</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="card card-primary">
                                    <!-- /.card-header -->
                                    <!-- form start -->

                                    <form action="<?=App::config('url')?>Category/updateCategory/<?=$id?>" id="update" method="post"  enctype="multipart/form-data">
                                        <div class="card-body">
                                            <?php foreach ($categoryNameTranslation as $translation):?>
                                                <?php if ('hr'===$translation->locale):?>
                                                    <div class="form-group">
                                                        <label for="name_hr">Naziv kategorije (HR)</label>
                                                        <input type="text" class="form-control" id="name_hr" name="name_hr" value="<?=$translation->name?>" placeholder="Unesite ime kategorije">
                                                    </div>
                                                <?php else:?>
                                                    <div class="form-group">
                                                        <label for="name_en">Naziv kategorije (EN)</label>
                                                        <input type="text" class="form-control" id="name_en" name="name_en" value="<?=$translation->name?>" placeholder="Unesite ime kategorije">
                                                    </div>
                                                <?php endif;?>
                                            <?php endforeach;?>
                                            <div class="form-group">
                                                <label for="active">Aktivna kategorija?</label>
                                                <input type="checkbox" class="form-control" id="active" name="active" placeholder="Aktivan" value="1" <?=$category['active']? 'checked' : '' ?>>
                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-primary">Spremi promjene</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer text-center">
                                <a href="<?= App::config("url") ?>Dashboard/categories" class="uppercase">pregled svih kategorija</a>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!--/. container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <?php require 'copyright.phtml'?>
    </footer>
</div>
<?php require "scripts.phtml"?>
</body>
</html>
