<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

<link rel="stylesheet" href="<?=App::config('url')?>assets/css/admin/OverlayScrollbars.min.css">
<link rel="stylesheet" href="<?=App::config('url')?>assets/css/admin/adminlte.css">

<!-- FontAwesome 5 -->
<link rel="stylesheet" href="https://matej.com.hr/FontAwesome/css/all.css">
<script src="https://matej.com.hr/FontAwesome/js/all.js"></script>