<?php

use Enum\OrdersEnum;

?>
<!doctype html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= App::config('nazivApp') ?></title>

    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php require 'headCss.phtml' ?>
</head>

<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">


    <?php require "navbar.phtml"?>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <?php require "side_navbar.phtml"?>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Kontrolna ploča</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <a href="" class="nav-link"></a>

                            <li class="breadcrumb-item"><a href="<?=App::config('url')?>">Trgovina</a></li>
                            <li class="breadcrumb-item active">Nadzorna ploča</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Info boxes -->
                <?php require 'header.phtml'?>
                <!-- /.row -->


                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Pregled narudžbi</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">

                                    <section>
                                        <div class="col-md-12">
                                            <table class="table table-bordered table-striped" id="userTable" width="100%">
                                                <thead>
                                                <tr>
                                                    <th>Order ID</th>
                                                    <th>Ukupna cijena proizvoda (poštarina)</th>
                                                    <th>Status narudžbe</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php

                                                foreach ($orders as $order):
                                                    ?>

                                                    <tr>
                                                        <td><a href="<?= App::config("url") ?>Dashboard/order/<?=$order->getId()?>"><?=$order->getId()?></a></td>
                                                        <td>€ <?=number_format((float) $order->getProductPrice(), 2) ?> | (€ <?=number_format((float) $order->getDeliveryPrice(), 2)?>)</td>
                                                        <td>
                                                            <?php switch ($order->getStatus()){
                                                                case OrdersEnum::getReceived():
                                                                    ?>
                                                                <span class="badge badge-info"><?=$order->getStatus()?></span>
                                                                <?php break;
                                                                case OrdersEnum::getFinished():
                                                                    ?>
                                                                    <span class="badge badge-primary"><?=$order->getStatus()?></span>
                                                                    <?php break;
                                                            case OrdersEnum::getCanceled():?>
                                                                <span class="badge badge-secondary"><?=$order->getStatus()?></span>
                                                                <?php break;
                                                            case OrdersEnum::getSent():?>
                                                                <span class="badge badge-success"><?=$order->getStatus()?></span>
                                                            <?php break;
                                                            case OrdersEnum::getOnHold():?>
                                                            <span class="badge badge-warning"><?=$order->getStatus()?></span>
                                                            <?php break;}
                                                            ?>
                                                        </td>
                                                        <td style="text-align: right">
                                                            <a href="<?= App::config("url") ?>Dashboard/order/<?=$order->getId()?>">
                                                                Pregled narudžbe
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach;?>
                                            </table>
                                        </div>
                                    </section>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->
                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!--/. container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <?php require 'copyright.phtml'?>
    </footer>
</div>
<?php require "scripts.phtml"?>
</body>
</html>
