<!doctype html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Project name</title>

    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php require 'headCss.phtml' ?>
</head>

<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">


    <?php require "navbar.phtml"?>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <?php require "side_navbar.phtml"?>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Kontrolna ploča</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <a href="" class="nav-link"></a>

                            <li class="breadcrumb-item"><a href="<?=App::config('url')?>">Trgovina</a></li>
                            <li class="breadcrumb-item active">Nadzorna ploča</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Info boxes -->
                <?php require 'header.phtml'?>
                <!-- /.row -->


                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Narudžba - <?=$order[0]->numeric_id?></h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <div class="text-center"><b>Popis proizvoda</b></div>
                                    <section>
                                        <div class="col-md-12">
                                            <table class="table table-bordered table-striped" id="userTable" width="100%">
                                                <thead>
                                                <tr>
                                                    <th>Proizvod</th>
                                                    <th class="text-center">Količina</th>
                                                    <th class="text-center">Cijena</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php foreach ($orderProducts as $orderProduct):?>
                                                    <tr>
                                                        <td><?=$orderProduct->name?></td>
                                                        <td class="text-center"><?=$orderProduct->product_quantity?></td>
                                                        <td class="text-center"><?=$orderProduct->product_price?> &euro;</td>
                                                        <td><a href="<?= App::config("url") ?>Dashboard/product/<?=$orderProduct->pid?>" class="float-right">Pregled proizvoda</a></td>
                                                    </tr>
                                                <?php endforeach;?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </section>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->
                            <!-- /.card-footer -->
                        </div>
                        <div class="card">
                            <div class="card-header border-transparent">


                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mt-5 text-center" style="padding-left: 10%; padding-right: 10%">
                                            <form action="<?=App::config('url')?>Order/changeStatus/<?=$order[0]->oid?>" id="changeStatus" method="post"  enctype="multipart/form-data">
                                                <div class="form-group">
                                                    <label for="status">Promjeni status narudžbe</label>
                                                    <select class="form-control" name="status" id="status">
                                                        <option value="Zaprimljeno" <?=$order[0]->status === 'Zaprimljeno' ? 'selected' : '' ?>>Zaprimljeno</option>
                                                        <option value="U obradi" <?=$order[0]->status === 'U obradi' ? 'selected' : '' ?>>U obradi</option>
                                                        <option value="Poslano" <?=$order[0]->status === 'Poslano' ? 'selected' : '' ?>>Poslano</option>
                                                        <option value="Završeno" <?=$order[0]->status === 'Završeno' ? 'selected' : '' ?>>Završeno</option>
                                                        <option value="Otkazano" <?=$order[0]->status === 'Otkazano' ? 'selected' : '' ?>>Otkazano</option>
                                                    </select>
                                                </div>
                                                <div class="mb-4">
                                                    <button type="submit" class="btn btn-primary">Spremi status</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <form action="<?=App::config('url')?>Order/changeComment/<?=$order[0]->oid?>" id="changeStatus" method="post"  enctype="multipart/form-data">
                                            <div class="form-group">
                                                <label for="comment">Administratorski komentar narudžbe</label>
                                                <textarea name="comment" id="comment" cols="50" rows="5"><?=$order[0]->comment?></textarea>
                                            </div>
                                            <div class="mb-4">
                                                <button type="submit" class="btn btn-primary">Spremi komentar</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->
                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Detalji narudžbe</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <section>
                                        <div class="col-md-12">
                                            <p>
                                                <h4>Korisnički podaci</h4>
                                            </p>
                                            <hr>
                                            <p><b>Ime:</b> <?=$order[0]->name?></p>
                                            <p><b>Prezime:</b> <?=$order[0]->surname?></p>
                                            <p><b>Adresa:</b> <?=$order[0]->address?></p>
                                            <p><b>Poštanski broj:</b> <?=$order[0]->postal?></p>
                                            <p><b>Grad:</b> <?=$order[0]->city?></p>
                                            <hr>
                                            <hr>
                                            <p>
                                            <h4>Podaci narudžbe</h4>
                                            </p>
                                            <hr>
                                            <p><b>Ukupni iznos proizvoda:</b> <?=$order[0]->product_price?> &euro;</p>
                                            <p><b>Ukupni iznos dostave:</b> <?=$order[0]->delivery_price?> &euro;</p>
                                            <h5><b>Ukupni iznos narudžbe:</b> <?=$order[0]->total_price?> &euro;</h5>
                                            <p><b>Metoda plaćanja:</b> <?=$order[0]->payment_method?> </p>
                                            <p><b>Status narudžbe:</b> <?=$order[0]->status?> </p>
                                            <p><b>Datum narudžbe:</b> <?= date('d.m.Y', strtotime($order[0]->created_at))?></p>
                                            <hr>
                                            <hr>
                                        </div>
                                    </section>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->
                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!--/. container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <?php require 'copyright.phtml'?>
    </footer>
</div>
<?php require "scripts.phtml"?>
</body>
</html>
