<?php

use Enum\OrdersEnum;
use Model\ShoppingCartModel;

?>
<!doctype html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= App::config('nazivApp') ?></title>

    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php require 'headCss.phtml' ?>

    <script src="<?= App::config("url") ?>assets/js/admin/tinymce.min.js" type="text/javascript" referrerpolicy="origin"></script>
</head>
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
    });
</script>


<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">


    <?php require "navbar.phtml"?>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <?php require "side_navbar.phtml"?>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Kontrolna ploča</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <a href="" class="nav-link"></a>

                            <li class="breadcrumb-item"><a href="<?=App::config('url')?>">Trgovina</a></li>
                            <li class="breadcrumb-item active">Nadzorna ploča</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Info boxes -->
                <?php require 'header.phtml'?>
                <!-- /.row -->


                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Proizvodi narudžbe</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">

                                    <section>
                                        <div class="col-md-12">
                                            <table class="table table-bordered table-striped" id="userTable" width="100%">
                                                <thead>
                                                <tr>
                                                    <th>Naziv proizvoda</th>
                                                    <th>Boja</th>
                                                    <th>Veličina</th>
                                                    <th>Cijena</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                /** @var ShoppingCartModel $orderProduct */
                                                foreach ($orderProducts as $orderProduct):?>
                                                <tr>
                                                    <td><?=ProductNameTranslation::getByProductModel($orderProduct->getProduct())->getName()?></td>
                                                    <td><?=$orderProduct->getColor()->getName()?></td>
                                                    <td><?=$orderProduct->getSize()->getName()?></td>
                                                    <td>€ <?=number_format($orderProduct->getProductPrice(), 2)?></td>
                                                    <td><a href="<?= App::config("url") ?>Dashboard/product/<?=$orderProduct->getProduct()->getId()?>" class="float-right">Pregled proizvoda</a></td>
                                                </tr>
                                                <?php endforeach;?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </section>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->

                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->

                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Komentari narudžbe</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">

                                    <section>
                                        <div class="col-md-12">
                                            <form action="<?=App::config('url')?>Order/changeComment/<?=$orderDetails->getId()?>" id="update" method="post">
                                                <div class="card-body">
                                                    <div class="form-group">
                                                        <label for="comment">Komentar</label><br>
                                                        <textarea name="comment" id="comment" class="form-control" style="width: 100%" rows="10"><?=$orderDetails->getComment()?></textarea>
                                                    </div>
                                                </div>
                                                <!-- /.card-body -->

                                                <div class="card-footer">
                                                    <button type="submit" class="btn btn-primary">Spremi komentar</button>
                                                </div>
                                            </form>
                                        </div>
                                    </section>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->

                            <!-- /.card-footer -->
                        </div>
                    </div>
                    <!-- /.col -->

                    <div class="col-md-4">

                        <!-- PRODUCT LIST -->
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Podaci o narudžbi</h3>
                                <?php
                               #tools::debug($orderDetails);
                                ?>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="card card-primary">
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                        <div class="card-body">
                                            <div class="form-group">
                                                <label for="name_hr">Podaci o korisniku</label>
                                                <p><span><b>Ime korisnika</b></span><span style="float: right"><?=$userDetails->getName()?></span></p>
                                                <p><span><b>Adresa</b></span><span style="float: right"><?=$userDetails->getAddress()?></span></p>
                                                <p><span><b>Mjesto</b></span><span style="float: right"><?=$userDetails->getCity()?></span></p>
                                                <p><span><b>Poštanski broj</b></span><span style="float: right"><?=$userDetails->getPostal()?></span></p>
                                                <p><span><b>Kontakt email</b></span><span style="float: right"><?=$user->getEmail()?></span></p>
                                                <p><span><b>Kontakt broj</b></span><span style="float: right"><?=$userDetails->getPhone()?></span></p>
                                            </div>
                                            <hr>
                                            <div class="form-group">
                                                <label for="name_hr">Iznos</label>
                                                <p><span><b>Način plaćanja</b></span><span style="float: right"><?=$orderDetails->getPaymentMethod()?></span></p>
                                                <p><span><b>Ukupna cijena proizvoda</b></span><span style="float: right">€ <?=number_format($orderDetails->getProductPrice(), 2)?></span></p>
                                                <p><span><b>Poštarina</b></span><span style="float: right">€ <?=number_format($orderDetails->getDeliveryPrice(), 2)?></span></p>
                                                <p><span><b>Ukupno</b></span><span style="float: right">€ <?=number_format($orderDetails->getTotalPrice(), 2)?></span></p>
                                            </div>
                                            <hr>
                                            <div class="form-group">
                                                <label for="name_hr">Status narudžbe</label>
                                                <p><span><b>Trenutni status</b></span><span style="float: right"><?=$orderDetails->getStatus()?></span></p>
                                                <p style="text-align: center; margin-top: 30px">Promjeni status</p>
                                                <form action="<?= App::config("url") ?>Order/changeStatus/<?=$orderDetails->getId()?>" method="post" id="changeStatus">
                                                    <select name="status" id="" style="width: 100%; padding: 10px 5px;">
                                                        <?php foreach (OrdersEnum::getStatusAsArray() as $enums):?>
                                                        <option class="form-control" value="<?=$enums?>" <?= $enums === $orderDetails->getStatus()? 'selected': ''?>><?=$enums?></option>
                                                        <?php endforeach;?>
                                                    </select>
                                                </form>
                                            </div>

                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-primary" form="changeStatus">Spremi</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!--/. container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <?php require 'copyright.phtml'?>
    </footer>
</div>
<?php require "scripts.phtml"?>
</body>
</html>
