<!doctype html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= App::config('nazivApp') ?></title>

    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php require 'headCss.phtml' ?>
</head>

<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">


    <?php require "navbar.phtml"?>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <?php require "side_navbar.phtml"?>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Kontrolna ploča</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <a href="" class="nav-link"></a>

                            <li class="breadcrumb-item"><a href="<?=App::config('url')?>">Trgovina</a></li>
                            <li class="breadcrumb-item active">Nadzorna ploča</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Info boxes -->
                <?php require 'header.phtml'?>
                <!-- /.row -->


                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Proizvodi</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">

                                    <section>
                                        <div class="col-md-12">
                                            <table class="table table-bordered table-striped" id="userTable" width="100%">
                                                <thead>
                                                <tr>
                                                    <th>Naziv</th>
                                                    <th>Aktivan proizvod</th>
                                                    <th>Cijena</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php
                                                /** @var \Dto\DashboardProductDto $product */
                                                foreach ($products as $product):?>
                                                <tr>
                                                    <td><?=$product->getName()?></td>
                                                    <td><?=$product->getActive() === 1 ? 'Da':'Ne'?></td>
                                                    <td><?=$product->getPrice()?> EUR</td>
                                                    <td><a href="<?= App::config("url") ?>Dashboard/product/<?=$product->getId()?>" class="float-right">Pregled proizvoda</a></td>
                                                </tr>
                                                <?php endforeach;?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </section>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->
                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->

                    <div class="col-md-4">

                        <!-- PRODUCT LIST -->
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Kreiraj novi proizvod</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="card card-primary">
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                    <form action="<?=App::config('url')?>Product/createProduct" method="post"  enctype="multipart/form-data">
                                        <div class="card-body">
                                            <div class="form-group">
                                                <label for="name_hr">Naziv proizvoda (HR)</label>
                                                <input type="text" class="form-control" id="name_hr" name="name_hr" placeholder="Unesite ime proizvoda">
                                            </div>
                                            <div class="form-group">
                                                <label for="name_en">Naziv proizvoda (EN)</label>
                                                <input type="text" class="form-control" id="name_en" name="name_en" placeholder="Unesite ime proizvoda">
                                            </div>
                                            <div class="form-group">
                                                <label for="price">Cijena proizvoda</label>
                                                <input type="number" class="form-control" id="price" name="price" placeholder="Unesite cijenu proizvoda" step=".01">
                                            </div>
                                            <div class="form-group">
                                                <label for="price_on_sale">Cijena proizvoda na popustu</label>
                                                <input type="number" class="form-control" id="price_on_sale" name="price_on_sale" placeholder="Unesite cijenu proizvoda na akciji" step=".01">
                                            </div>
                                            <div class="form-group">
                                                <label for="active">Aktivan proizvod?</label>
                                                <input type="checkbox" class="form-control" id="active" name="active" placeholder="Aktivan" value="1">
                                            </div>
                                            <div class="form-group">
                                                <label for="active_sale_price">Aktivan popust?</label>
                                                <input type="checkbox" class="form-control" id="active_sale_price" name="active_sale_price" placeholder="Aktivan" value="1">
                                            </div>

                                            <input type="hidden" name="description_hr" value="">
                                            <input type="hidden" name="description_en" value="">

                                            <div class="form-group">
                                                <label for="featured">Istaknut proizvod?</label>
                                                <input type="checkbox" class="form-control" id="featured" name="featured" placeholder="Istaknut" value="1">
                                            </div>
                                            <div class="form-group">
                                                <label for="sku_number">SKU broj</label>
                                                <input type="number" class="form-control" id="sku_number" name="sku_number" placeholder="Unesite sku broj ako postoji" step="1">
                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-primary">Spremi</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!--/. container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <?php require 'copyright.phtml'?>
    </footer>
</div>
<?php require "scripts.phtml"?>
</body>
</html>
