<!doctype html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Project name</title>

    <meta property="og:title" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php require 'headCss.phtml' ?>
</head>

<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">


    <?php require "navbar.phtml"?>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <?php require "side_navbar.phtml"?>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Kontrolna ploča</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <a href="" class="nav-link"></a>

                            <li class="breadcrumb-item"><a href="<?=App::config('url')?>">Trgovina</a></li>
                            <li class="breadcrumb-item active">Nadzorna ploča</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Info boxes -->
                <?php require 'header.phtml'?>
                <!-- /.row -->


                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Proizvod - uređivanje slike</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <div class="row">
                                        <div class="col-6 text-center" style="padding: 5%"><img src="<?= App::config("url") ?>assets/images/productImages/<?=$product['image']?>" alt="" style="width: 100%"></div>
                                        <div class="col-5 text-left" style="width: 80%; margin-top: 10%">
                                            <label class="custom-file-label" for="exampleInputFile">Odabir slike</label>
                                            <input type="file" name="myfile" class="custom-file-input" id="exampleInputFile" form="update" >
                                        </div>
                                    </div>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->

                            <!-- /.card-footer -->
                        </div>

                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Proizvod - kategorije</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <section>
                                        <div class="col-md-12">
                                            <table class="table table-bordered table-striped" id="userTable" width="100%">
                                                <thead>
                                                <tr>
                                                    <th>Naziv kategorije</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <?php $activeCategories = [];?>
                                                <?php foreach ($productCategories as $productCategory):?>
                                                <?php $activeCategories[] = $productCategory->category_id?>
                                                    <tr>
                                                        <td><?=$productCategory->name?></td>

                                                        <td><a href="<?= App::config("url") ?>Product/deleteProductCategory/<?=$productCategory->id?>?p=<?=$id?>" class="float-right">Ukloni kategoriju</a></td>
                                                    </tr>
                                                <?php endforeach;?>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="mt-5 text-center" style="padding-left: 10%; padding-right: 10%">
                                            <form action="<?=App::config('url')?>Product/createProductCategory/<?=$id?>" id="addCategory" method="post"  enctype="multipart/form-data">
                                                <div class="form-group">
                                                    <label for="category">Dodaj kategoriju</label>
                                                    <select class="form-control" name="category_id" id="category">
                                                        <?php foreach ($categories as $category):?>
                                                        <?php if (in_array($category->id, $activeCategories)) {continue;}?>
                                                        <option value="<?=$category->id?>"><?=$category->name?></option>
                                                        <?php endforeach;?>
                                                    </select>
                                                </div>
                                                <div class="mb-4">
                                                    <button type="submit" class="btn btn-primary">Spremi kategoriju</button>
                                                </div>
                                            </form>
                                        </div>
                                    </section>

                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->

                            <!-- /.card-footer -->
                        </div>

                        <div class="card">
                            <div class="card-header border-transparent">
                                <h3 class="card-title">Proizvod - brisanje</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="table-responsive">
                                    <section>
                                        <div class="mt-5 text-center" style="padding-left: 10%; padding-right: 10%">
                                            <div class="form-group">
                                                <a href="<?=App::config('url')?>Product/deleteProduct/<?=$id?>" class="btn btn-danger">Obriši proizvod</a>
                                            </div>
                                        </div>
                                    </section>

                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <!-- /.card-body -->

                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->

                    <div class="col-md-4">

                        <!-- PRODUCT LIST -->
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Uređivanje proizvoda</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <div class="card card-primary">
                                    <!-- /.card-header -->
                                    <!-- form start -->

                                    <form action="<?=App::config('url')?>Product/updateProduct/<?=$id?>" id="update" method="post"  enctype="multipart/form-data">
                                        <div class="card-body">
                                            <?php foreach ($productNameTranslation as $translation):?>
                                            <?php if ('hr'===$translation->locale):?>
                                            <div class="form-group">
                                                <label for="name_hr">Naziv proizvoda (HR)</label>
                                                <input type="text" class="form-control" id="name_hr" name="name_hr" value="<?=$translation->name?>" placeholder="Unesite ime proizvoda">
                                            </div>
                                            <?php else:?>
                                            <div class="form-group">
                                                <label for="name_en">Naziv proizvoda (EN)</label>
                                                <input type="text" class="form-control" id="name_en" name="name_en" value="<?=$translation->name?>" placeholder="Unesite ime proizvoda">
                                            </div>
                                            <?php endif;?>
                                            <?php endforeach;?>
                                            <div class="form-group">
                                                <label for="price">Cijena proizvoda</label>
                                                <input type="number" class="form-control" id="price" name="price" value="<?=$product['price']?>" placeholder="Unesite cijenu proizvoda" step=".01">
                                            </div>
                                            <div class="form-group">
                                                <label for="price_on_sale">Cijena proizvoda na popustu</label>
                                                <input type="number" class="form-control" id="price_on_sale" name="price_on_sale" value="<?=$product['price_on_sale']?>" placeholder="Unesite cijenu proizvoda na akciji" step=".01">
                                            </div>
                                            <div class="form-group">
                                                <label for="active_sale_price">Aktivan popust?</label>
                                                <input type="checkbox" class="form-control" id="active_sale_price" name="active_sale_price" placeholder="Aktivan" value="1" <?=$product['active_sale_price']? 'checked' : '' ?>>
                                            </div>
                                            <div class="form-group">
                                                <label for="available">Dostupna količina</label>
                                                <input type="number" class="form-control" id="available" name="available" placeholder="Unesite količinu dostupnih proizvoda" value="<?=$productQuantity['available']?>" step="1">
                                            </div>
                                            <?php foreach ($productTranslation as $translation):?>
                                            <?php if ('hr'===$translation->locale):?>
                                            <div class="form-group">
                                                <label for="description_hr">Opis proizvoda (HR)</label>
                                                <textarea class="form-control" rows="3" placeholder="Enter ..." id="description_hr" name="description_hr"><?=$translation->description?></textarea>
                                            </div>
                                            <?php else:?>
                                            <div class="form-group">
                                                <label for="description_en">Opis proizvoda (EN)</label>
                                                <textarea class="form-control" rows="3" placeholder="Enter ..." id="description_en" name="description_en"><?=$translation->description?></textarea>
                                            </div>
                                            <?php endif;?>
                                            <?php endforeach;?>
                                            <div class="form-group">
                                                <label for="active">Aktivan proizvod?</label>
                                                <input type="checkbox" class="form-control" id="active" name="active" placeholder="Aktivan" value="1" <?=$product['active']? 'checked' : '' ?>>
                                            </div>
                                            <div class="form-group">
                                                <label for="sku_number">SKU broj</label>
                                                <input type="number" class="form-control" id="sku_number" name="sku_number" placeholder="Unesite sku broj ako postoji" step="1" value="<?=$product['sku_number']?>">
                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-primary">Spremi promjene</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer text-center">
                                <a href="<?= App::config("url") ?>Dashboard/products" class="uppercase">pregled svih proizvoda</a>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!--/. container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <?php require 'copyright.phtml'?>
    </footer>
</div>
<?php require "scripts.phtml"?>
</body>
</html>
