<!-- Main JS -->
<script src="<?= App::config("url") ?>assets/js/admin/scripts.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/jquery.min.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/jquery.overlayScrollbars.min.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/adminlte.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/jquery.mousewheel.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/raphael.min.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/jquery.mapael.min.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/usa_states.min.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/Chart.min.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/dashboard2.js"></script>
<script src="<?= App::config("url") ?>assets/js/admin/bootstrap.bundle.min.js"></script>

<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
<script>
    $(document).ready(function() {
        $('#userTable').DataTable();
    });
</script>
